- title: 菲斯曼壁挂炉
  img: 20140412100507994.jpg
  url: www.baidu.com
  id: 3

- title: 德国威能turboTEC 标准型燃气壁挂式采暖/热水锅炉
  img: 20140411170817466.jpg
  url: parkr
  id: 2

- title: 德国威能turboTEC豪华型燃气壁挂式锅炉
  img: 20140411170434304.jpg
  url: liufengyun
  id: 1


